title: Ira Chartarum
email: info@ira-chartarum.com
description: >- 
  Trading cards meet tabletop. A complex strategic game for core gamers who love deep-diving into intricate mechanics.
baseurl: "/ira-chartarum-landingpage"
url: "https://www.ira-chartarum.com"
twitter_username: 
github_username: grammes

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - memory-bank/
  - requirements/
